# Site
repository: Git repository where your resume will be hosted, only required if you are hosting on GitHub (eg. sproogen/modern-resume-theme)
# favicon: Directory of your favicon (eg. images/favicon.ico)(optional)

# Personal info
name: Rishikesh raj
title: Software Developer
email: rishikeshrajrxl@gamil.com 
phone: +91-9521864647 
website: rishikeshraj.com

darkmode: false

# Social links
#twitter_username: jekyllrb
github_username:  Rishikeshrajrxl
#stackoverflow_username: "00000001"
#dribbble_username: jekyll
facebook_username: rishikesh.raj.5059
#flickr_username: jekyll
instagram_username: thisisrishikeshraj
linkedin_username: rishikesh-raj-65065b180
#xing_username: jekyll
#pinterest_username: jekyll
youtube_username: channel/UCkRiZHvzNdxNyPHuTPXgVFA?view_as=subscriber
#googleplus_username: +jekyll
#orcid_username: 0000-0000-0000-0000



# About Section
about_title: About Me 
about_profile_image: profile2.jpeg 
about_content: | # this will include new lines to allow paragraphs
  I am Computer Science and Engineering (CSE) Undergraduate at Arya Institute of Engineering & Technology in my 2nd year. 
  Working with computer programmers and professionals to solve problems and create products. I'm eager to learn and expand my knowledge 
  and always curious to learn things by doing.
  I have a profound interest in programming, application development,web development,Database handling. 
  I am a self-driven person with established goals and plans to achieve them. I have always been success-oriented, and will always work
  towards achieving more.
  In my free time I love to code at below Given Platform.
    
    - <a href="https://www.hackerrank.com/rishikeshraj">Hackerrank</a>
    - <a href="https://auth.geeksforgeeks.org/user/rishikeshrajrxl/practice/">GeeksforGeeks</a>
    - <a href="https://leetcode.com/rishikeshrajrxl/">Leetcode</a>
    

# Projects Section
# projects_title: Projects #(Use this to override about projects section title)

# Experience Section
# experience_title: Experience #(Use this to override about experience section title)

# Education Section
#education_title: Education #(Use this to override about education section title)

# More Section
# more_title:Skills #(Use this to override about more section title)
more_content: | # this will include new lines to allow paragraphs
  - **Programming:** JAVA, C++, HTML, CSS, PHP
  - **Database:**  MYSQL
  - **Packages:**   JAVA-SWING
  - **Course:**    DATA STRUCTURE & ALGORITHM
  
# More Section(Certification)
# more_title:Certification #(Use this to override about more section title)
more_content2: | # this will include new lines to allow paragraphs
  - <a href="http://www.linkedin.com/learning/php-with-mysql-essential-training-1-the-basics"> **PHP with MySQL Essential Training** </a>
  - <a href="https://www.coursera.org/account/accomplishments/verify/CBPD3RA59UN7"> **Introduction To Web Development** </a>
  - <a href="http://www.linkedin.com/learning/introduction-to-data-structures-algorithms-in-java">**Data Structure & Algorithms in Java** </a>
  - <a href="https://www.coursera.org/account/accomplishments/verify/5VQRSNZAGZLR">**Programming with HTML and CSS**  </a>
  - <a href="http://https//LEARNDIGITAL.WITHGOOGLE.COM/DIGITALUNLOCKED/validate-certificate-code">**Fundamental of Digital Marketing**  </a>
  
# More Section
# more_title:Hobies #(Use this to override about more section title)
more_content3: | # this will include new lines to allow paragraphs
  - **Programming** 
  - **Listening Music** 
  - **Reading**   
   
  
  


  
# Footer
footer_show_references: true

# Build settings
# theme: modern-resume-theme (Use this is you are hosting your resume yourself)
# remote_theme: sproogen/modern-resume-theme (Use this if you are hosting your resume on GitHub)

sass:
  sass_dir: _sass
  style: compressed

plugins:
 - jekyll-seo-tag

exclude : [
  "Gemfile",
  "Gemfile.lock",
  "node_modules",
  "vendor/bundle/",
  "vendor/cache/",
  "vendor/gems/",
  "vendor/ruby/",
  "lib/",
  "scripts/",
  "docker-compose.yml",
  ]
